# Blog Identity
blog_name: "The Agentic Engineer"
domain: "the-agentic-engineer.com"

# Paths
website_dir: "website"
content_dir: "website/content/posts"
public_images_dir: "website/public/blog"

# Image generation
image_generation:
  default_size: "1024x1024"
  format: "webp"
  quality: 85

# Categories (validation reference)
categories:
  - tutorials
  - case-studies
  - guides
  - lists
  - comparisons
  - problem-solution
  - opinions
