# Blog Identity
blog_name: "The Agentic Engineer"
domain: "the-agentic-engineer.com"

# Paths
website_dir: "website"
content_dir: "website/content/posts"
public_images_dir: "website/public/blog"

# Image generation
image_generation:
  default_size: "1024x1024"
  format: "webp"
  quality: 85

# Publishing schedule
publishing:
  frequency: "twice-weekly"  # or "weekly" for single-day publishing
  days: ["monday", "thursday"]  # Day(s) of week for regular schedule (can publish any day)
  time: "11:00:00"  # Publish time (UTC) - 6am EST - posts go live for ISR

# Categories (validation reference)
categories:
  - tutorials
  - case-studies
  - guides
  - lists
  - comparisons
  - problem-solution
  - opinions
